site_name: Cours Python & ArcPy
site_description: Initiation à Python et ArcPy
site_url: https://abdoulhakimelmi-lang.github.io/cours-arcpy/

theme:
  name: material
  language: fr

nav:
  - Accueil: index.md
  - Cours Python & ArcPy: cours-arcpy.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
